### ISSUE TITLE
Implement Worksite Filters in Create New Team

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#1032]
## Description
Add a cases filter when creating a new team, which should include lists.
## Screenshots
![Screenshot 2024-08-08 160022](https://github.com/user-attachments/assets/0eb0c506-8f22-4e3b-b9c5-793f406a53f4)

**Comment by deepanchal** [comment]
Add worksite filter in red box so that you can filter worksites shown below
