### ISSUE TITLE
make dashboard page look better

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-4-web#156]
The dashboard page is the first thing you see when you log in.  It should just look better.  It screams un-finished (which is pretty accurate at this stage) and could use a little sprucing.
- [ ] make it look awesomer.
- [ ] It also needs to look good from a phone.  

This is the current dashboard page. 
![image](https://user-images.githubusercontent.com/699333/78501249-7f806080-7720-11ea-9f8d-767db6f0993c.png)

This is the dashboard page design doc in InVision:  
**Option 1:** 
https://projects.invisionapp.com/d/main#/console/14746784/399284412/preview
![image](https://user-images.githubusercontent.com/699333/78501285-accd0e80-7720-11ea-8914-205302401441.png)

**or option 2:**
https://projects.invisionapp.com/d/main#/console/14746784/399284411/preview
![image](https://user-images.githubusercontent.com/699333/78501301-c9694680-7720-11ea-8d91-4986debfa9c6.png)

Finally, my intention is to add the call center stats block from the home page and add it to this main dashboard.

**Current form:**  
![image](https://user-images.githubusercontent.com/699333/78501365-10573c00-7721-11ea-8d44-8d285d8a3daf.png)

**Form is should look like**
![image](https://user-images.githubusercontent.com/699333/78501380-2d8c0a80-7721-11ea-959d-356213088f77.png)
https://github.com/CrisisCleanup/crisiscleanup-3-web/issues/383

**Comment by aarontitus** [comment]
Superseded by #784
