### ISSUE TITLE
Extra help

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-4-web#161]
We need a new tab where we can share additional help suggestions and items:  

- [ ] Add a new tab next to News | Training  called "User Guide". 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/699333/96368074-58670a80-1117-11eb-9623-76cb5c7c4efe.png">
basically just clone what we have for news.

- [ ] Via localizations, we will add articles
1.  a link to the google document manual that volunteer Laurie Roe made
2.  something Aaron said.... I forgot.. 
3.  how to turn off pop up blocker
4.  how to change the status of a case
5.  another mini tip
6.  another mini trick
7.  so on and so forth.

**Comment by deepanchal** [comment]
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/46167867/c78fd5d0-6187-4684-980b-c0f28d3a5f1e)
