### ISSUE TITLE
Remove "Debug" Yellow Buttons, or Toggle on Profile

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#195]
I didn't realize until recently that the two yellow "Debug User" and "Debug Incident States" buttons appear for everyone, all the time, on all screens.
Please turn these off by default, and either add the buttons to a user's profile, or add a checkbox on the user profile to "Turn on Debugging," which would make these yellow buttons appear on every page. You could probably store the setting in the `user.settings` json object.

![Image](https://user-images.githubusercontent.com/4184619/227881987-06ac3501-b5d2-45d6-ad2b-0ac136da4c08.png)

**Comment by deepanchal** [comment]
Caused by https://github.com/CrisisCleanup/crisiscleanup-4-web/blob/master/src/store/modules/acl.ts#L33-L36
