### ISSUE TITLE
Add "No Current Hotlines" to Phone Page Between Incidents

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#270]
When there are no current hotlines, add `phoneDashboard.currently_closed` to the top of https://www.crisiscleanup.org/phone, where the hotline numbers are typically listed.

**Comment by deepanchal** [comment]
@aarontitus I can't find the container where we typically list hotlines on phone page. Can you please help me find it with some screenshots? I also tried looking for a ribbon component which might list hotlines but we don't have one.

**Comment by deepanchal** [comment]
I think I misunderstood the issue? Do you want to replace these hotline numbers with `phoneDashboard.currently_closed`?



![Image](https://user-images.githubusercontent.com/46167867/236694830-279caa91-f5f9-43f1-804a-c8e4fbf52d86.png)

**Comment by aarontitus** [comment]
@deepanchal Sorry for my tardy response.

- When there one or more current hotline, display them.
- In-between disasters, when there is no open hotline, display `homeVue.phone_or_website`, which is "No Current Hotlines."
- This is for /phone, /login, and all public pages.
Hope that helps.
