### ISSUE TITLE
Dev Cannot Save Cases

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#350]
Bug: Try to create a case on Dev. 500 error results. Confirmed 7/12, long after it should have been fixed.

**Comment by BradenM** [comment]
@aarontitus @tabiodun 
IIRC, this may have been related to the prior iteration of the dbsync?
Correct me if Im wrong about that.

Otherwise though, can we confirm if its still occuring with the new implementation of dbsync?

**Comment by aarontitus** [comment]
Confirmed OK.
