### ISSUE TITLE
Copy Android app link verification file during build

### ISSUE THREAD

**Issue by hueachilles** [CrisisCleanup/crisiscleanup-4-web#415]
## Description
Android app links allow Android apps to intercept and process URLs of a specified domains.
One of the [verification methods](https://developer.android.com/training/app-links/verify-android-applinks#multiple-apps) is to expose a static file under the domain at the path `https://domain.name/.well-known/assetlinks.json`.

## Tasks
I've created a branch and added asset link verification files for production and non-production (nonp) environments.
I need the build process to copy the correct file for each environment and rename it to `assetlinks.json` in the same dir.
I'm assuming placing the `.well-known` dir under `public` will make these files accessible under `https://domain.name/.well-known/assetlinks.json`

**Comment by BradenM** [comment]
@qui van On the assetlinks,

Seeing as its an array:
https://github.com/CrisisCleanup/crisiscleanup-4-web/compare/master...feat/configure-android-app-link

Is there a reason we couldn't just use a single static assetlinks file with all the entries?

Will you also need to be able to intercept api.crisiscleanup.org?
