### ISSUE TITLE
Auth Failure

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#565]
**Additional Information:**
- Environment:
- Version:
- Ticket Submitted From: **https://www.crisiscleanup.org/o/callback?code=7Kd7D1ay4q1WlNTBrsJUHTv5SgBYcE&state=%2F**
- Zendesk Username: **Joshua Smith**
- Crisis Cleanup Username: **Josh Smith**
- Organization: **New Castle County Office of Emergency Management**
- CC Age: **2 months ago**

**Pictures:**

**Comments:**
```
I haven't been able to access website at all since lastnight?
```
This sounds like an authentication issue. I had him clear cache.

**Comment by BradenM** [comment]
:thinking: Not sure if this was prior to the completion of the authentication overhauls / fixes.

Have this reoccured since @aarontitus?
