### ISSUE TITLE
Phone Status Cosmetic issue

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup-4-web#60]
The buttons overlap the notes field.    need to do some cosmetic re-shuffling. 

![Image](https://user-images.githubusercontent.com/699333/219227240-5023657e-41dd-4d80-84fd-3cf95c847807.png)

**Comment by aarontitus** [comment]
Overlapping issue still remains. FF.


![Image](https://user-images.githubusercontent.com/4184619/223823373-4cdd32a5-1796-4780-a17b-c4f87de6ca02.png)
