### ISSUE TITLE
Activate Share Button on Cases

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#61]
When a user clicks the "Share" button on a case:
1. They can email a copy of the PDF file to one or more people, by either copying and pasting email addresses, or selecting users from a list. You can come up with a default email template, and I'll prettify it. Users should also be able to add a paragraph of their own, which will be inserted into the email body.
2. They can send a text message (SMS) to one or more people, by either copying and pasting phone numbers, or selecting users from a list. The SMS should contain:
  - "[user_first_name] [user_last_name] ([user_phone_number]) has assigned you case [case_number]:"
  - Survivor Name
  - Address
  - Phone number(s)
  - List of work types claimed by the organization
  - A link to update the case and view photos (ideally a bit.ly short link)
  - Optional notes from the sending user

Each of these actions should automatically claim the case on behalf of the organization. If the person does not want to claim the case, they must indicate why, just as when they print normally.

**Comment by aarontitus** [comment]
I cannot tell whether this works, because the messages are not logged in `message_messages`.

**Comment by tabiodun** [comment]
Seems to work. See https://api.staging.crisiscleanup.io/ccadmin/messagesapp/message/

**Comment by tabiodun** [comment]
I'm using django admin as a proxy for the messages table

**Comment by aarontitus** [comment]
I just confirmed that the messages were logged. Closing.
