### ISSUE TITLE
Incident Icon Not Displaying

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#677]
## Description
The icon showing the incident type (flood, fire, etc.) does not appear. See screenshot. FF.

## Screenshots
![Issue-No Incient Icon](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/4167e082-94df-4b79-8440-1533b0e72c55)

**Comment by deepanchal** [comment]
Can be fixed by implementing #771
