### ISSUE TITLE
Yellow Case Button Display Error

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#678]
## Description
For some reason, some of the yellow case buttons are not displaying. FF.

## Screenshots
![Issue-Missing worksite button](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/86bd214f-7200-4eba-9653-462178629bb5)

**Comment by deepanchal** [comment]
This issue is caused by not having `width` and `height` field on the sticky not svg icon. Chrome renders it fine without those properties but firefox doesn't. We need to make sure that width and height fields exists on a svg before adding it to repo.

Before:
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
    <path d="M312 320h136V56c0-13.3-10.7-24-24-24H24C10.7 32 0 42.7 0 56v400c0 13.3 10.7 24 24 24h264V344c0-13.2 10.8-24 24-24zm129 55l-98 98c-4.5 4.5-10.6 7-17 7h-6V352h128v6.1c0 6.3-2.5 12.4-7 16.9z" />
</svg>
```

After:
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100" height="100">
    <path d="M312 320h136V56c0-13.3-10.7-24-24-24H24C10.7 32 0 42.7 0 56v400c0 13.3 10.7 24 24 24h264V344c0-13.2 10.8-24 24-24zm129 55l-98 98c-4.5 4.5-10.6 7-17 7h-6V352h128v6.1c0 6.3-2.5 12.4-7 16.9z" />
</svg>
```
