### ISSUE TITLE
Other Organizations: Link to Cases Broken

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#76]
1. Click the "Cases Overdue" link.
2. Error: 404 page.
3. Should go to a link like: https://www.crisiscleanup.org/incident/254/work/new?showTable=true&work_type__claimed_by=426&work_type__status__in=open_unassigned,open_unresponsive,open_assigned,open_needs-follow-up,open_partially-completed&created_at__lte=2023-02-18T15%3A57%3A30.361Z
4. Note: I'm not sure if this functionality has been enabled on /work. It's currently going to /cases.

**Comment by deepanchal** [comment]
This issue is partially fixed by #119
The filters passed by `/other_organizations` page aren't loading on the worksite view page.
![image](https://user-images.githubusercontent.com/46167867/223847964-cb94963f-d8a9-4280-a7dd-b0b9433f81d2.png)

**Comment by aarontitus** [comment]
This still doesn't work on Staging...

**Comment by aarontitus** [comment]
This works, but creates a new issue: There is no way to turn it off :-). Closing this one and opening a new issue.
