### ISSUE TITLE
Add Red "Delete Account" button to /profile

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#782]
## Description
Please add a red button at the bottom of /profile to "Delete Account". This button should be a link to https://crisiscleanup.zendesk.com/hc/en-us/articles/25053795283597-Deleting-Your-User-Account
## Screenshots
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/792fbf88-6f81-481f-b7d1-c8e3c890d80b)

**Comment by deepanchal** [comment]
@aarontitus You'll need to add the following localizations:
- `profileUser.delete_account_link` -> Link to the blog post (ex. 'https://crisiscleanup.zendesk.com/hc/en-us/articles/25053795283597-Deleting-Your-User-Account')
- `profileUser.delete_account` -> button text (ex. 'Delete Account')
- `profileUser.delete_account_icon_alt` -> delete account external link icon alt text (ex. 'external-link-icon')
- `profileUser.delete_account_info` -> delete account button info text below the button

   ![Image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/46167867/82516a38-e143-4163-9d2d-9e3bbe4188f9)
