### ISSUE TITLE
Request Access Does not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#79]
https://app.staging.crisiscleanup.io/request_access: "Volunteer with Your Org" does not work.

**Comment by tabiodun** [comment]
I just tried it and it worked. What are you seeing?

**Comment by aarontitus** [comment]
Nothing happens when you click "Volunteer with Your Org." FF.


![Image](https://user-images.githubusercontent.com/4184619/223796065-636d25d0-1bb8-47e0-9cd0-58087cc02927.png)
