### ISSUE TITLE
Reports: Link does not work. Modal Empty.

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#82]
https://app.staging.crisiscleanup.io/reports
1. Link to the working report (i.e. /report/22) does not work. It just comes up with the standard "Reports Activation" modal.
2. The "Reports Activation" modal is empty.

![Image](https://user-images.githubusercontent.com/4184619/221260429-9c1b6f66-84d6-4d79-b3fe-caca634b3c05.png)

**Comment by tabiodun** [comment]
Noted the modal issue, but linking to existing report also works for me:



![Image](https://user-images.githubusercontent.com/1372010/221358834-a4add678-2bac-42c5-8603-4f25ed5cd62b.png)

**Comment by aarontitus** [comment]
Looks good.
