### ISSUE TITLE
Add Purge Images from Worksite for Survivors and Users

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#843]
## Description
On at least two occasions survivors have called the hotline because they have accidentally uploaded confidential information from their phones. We need the ability for survivors and users to completely purge photos. I.e., when they delete the file, it needs to be completely purged and deleted from our servers, including any older copies of the same file. If they don't want it on our servers, then I don't want it on our servers.

UPDATE: As signed images expire within 24 hours, all we need to do is make the "Delete" icon permanent on images for survivors (`crisiscleanup.org/s/xxxxxx`) and volunteers (rather than a hover, which does not work on mobile), and this should be sufficient. 

## Screenshots
![confidential](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/c7b2bb30-27fe-4408-a2b1-ec7749ab57ac)

## Tasks
1. On https://crisiscleanup.org/s/[xxxxxxxx], add the ability to delete/purge file.
2. On https://www.crisiscleanup.org/incident/[000]/work/[000000], change the delete function (when you hover over the photo) to a purge function.

**Comment by deepanchal** [comment]
@DatGamingStache We need these trash icons to be visible at all time (not just when hovered). Can you make these delete buttons on these images persistent?


![Image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/46167867/772f3278-4495-47fe-91bf-3ff20cb617bc)

**Comment by DatGamingStache** [comment]
Sure will tackle this in morning

**Comment by deepanchal** [comment]
Closed by https://github.com/CrisisCleanup/crisiscleanup-4-web/commit/a1af018c264662acb597c815ba5b0c977cb92498
