### ISSUE TITLE
Add "Work View" Button on Worksite Edit View (Replace Pencil with Briefcase)

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#846]
## Description
On the "Work View" of a case, there is a yellow edit pencil at the top of the page:
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/cc30d0fb-03c7-4a57-a522-d53812f3af80)

However, when you click the edit pencil and enter edit view, there is no way to get back to the Work View:
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/24c1bd2c-f6b5-42f5-8582-a6da54679deb)

## Tasks
Solution: Add a "Work" Briefcase icon where the pencil icon goes, in the worksite edit view:
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/edf69ee5-16ea-427d-98da-1db9d6a73df9)

**Comment by DatGamingStache** [comment]
in progress have ui button for it, but having issues with states on worksites
