### ISSUE TITLE
Wrong Incident Flag Improvements

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#849]
## Description
Worksites are regularly placed on the wrong incident.

- [x] Re-order the flags consistent with the screenshot below.
- [x] It still takes 30-45 seconds to load the incident list. We really, really need to fix this.
- [x] Also, please limit the list to the last two months of incidents.

## Screenshots
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/90befd0c-847e-4ee2-9de3-e9c28a10f4bb)
![image](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/4184619/66c4ed42-4625-41ee-95e7-4b5616d41764)

**Comment by deepanchal** [comment]
Fixed by https://github.com/CrisisCleanup/crisiscleanup-4-web/compare/0916ef01...79cb4dec
