### ISSUE TITLE
Admin Edit Org: Group Dropdown Empty Until Search

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#88]
You shouldn't need to search to see the groups. Also, it should be wide enough to accommodate all group names, like "The Church of Jesus Christ of Latter-day Saints.

![Image](https://user-images.githubusercontent.com/4184619/221267808-5bd9c5dc-ff6b-4d8d-a45e-99e06e98f380.png)

**Comment by tabiodun** [comment]
I think this is existing behaviour of having to search first (do we want this to be going forward?). I can increase the size of the dropdown though

**Comment by aarontitus** [comment]
Hmmm... I'm pretty sure it isn't. Because I am accustomed to seeing a list when I click the dropdown. In any case, I probably need to change, "this list is empty" to "search."
I'd like to increase the size of the list, please.

**Comment by aarontitus** [comment]
This almost works as anticipated. When I first click the dropdown, "Group (optional)" appears. Next, I search, and all of the options appear. Is it possible to have the contents of the dropdown load `onFocus()` or something?

**Comment by aarontitus** [comment]
Looks good!
